### ISSUE TITLE
Infografía Fundamentos de Ingeniería de Software

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/infografia-IsraelNicolas61#2]
[Infografía Fund. Ing. de Soft..pdf](https://github.com/SistemasTecTlaxiaco/infografia-IsraelNicolas61/files/7149049/Infografia.Fund.Ing.de.Soft.pdf)

**Comment by DuilioAquino10** [comment]
Calificación 20.
Califico: Duilio Ruben Aquino López.

**Comment by DuilioAquino10** [comment]
Calificación 18.
Califico: Duilio Ruben Aquino López.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
